### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [mark99i/AppSearcher#3]
Thanks for making your app available here, so other affected (and concerned) people can use it! However, there's the question of whether they can also *share* it, as you didn't declare a license. Would you consider doing so? Assuming you are open to "wide and easy distribution without difficult terms", I guess MIT would be a good choice. But any other OSI/FSF approved FOSS license (here's a helpful [list to choose from](https://spdx.org/licenses/)) would do as well. Thanks in advance!

**Comment by mark99i** [comment]
Thanks. Added MIT licence

**Comment by IzzySoft** [comment]
Wonderful, thanks! In about an hour, your app becomes [available in my repo](https://apt.izzysoft.de/packages/ru.mark99.appsearcher/) so it will be easier to discover (for people using an [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) and having my repo enabled), install and keep updated. Some considerations:

* you have no dedicated app icon, so your app will just use Android's standard green robot. You might wish to create and use your own.
* WebSearch: Currently, the selection is limited to Yandex and Google. Both are proprietary search engines not exactly known to be privacy-friendly. You might wish to add some more privacy-friendly ones (e.g. DuckDuckGo, Startpage, Gruble, Mojeek) or offer an option to configure a custom engine.
* To keep the app description up-to-date and be able to e.g. add/replace screenshots, add to the list of features etc., you could consider setting up Fastlane (I can offer a PR to provide you with a starter package which you then can build upon, and use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for assistance). Fastlane is the de-facto standard most Android apps use for that. Just let me know if I shall open that PR.

But for now, I hope you enjoy the boosted audience!

![image](https://github.com/mark99i/AppSearcher/assets/6781438/6fddc749-55d6-46ef-bbfd-039d852adfad)

**Comment by IzzySoft** [comment]
Oh, PS: you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to your app in my repo e.g. from your README :smiley:

**Comment by mark99i** [comment]
> you have no dedicated app icon, so your app will just use Android's standard green robot. You might wish to create and use your own.  

I thought about it, but since the icon is hidden in the launcher, there is no search in the list of recently opened applications, it turns out that it is only in the list of installed applications and in the store. maybe I'll add it later

> WebSearch: Currently, the selection is limited to Yandex and Google

good idea. I will consider providing a url input field for using any web search engine.

> To keep the app description up-to-date and be able to e.g. add/replace screenshots, add to the list of features etc., you could consider setting up Fastlane

> Oh, PS: you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to your app in my repo e.g. from your README

thank you for your interest, I will be glad to see the PR.
